apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    role: edit
    user: sam@statcan.gc.ca
  name: user-sam-statcan-clusterrole-edit
  namespace: sam
spec:
  rules:
  - when:
    - key: request.headers[kubeflow-userid]
      values:
      - sam@statcan.gc.ca
