apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressNoHostnames
metadata:
  name: ingress-no-hostnames
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
