apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SecuredGateways
metadata:
  name: secured-gateways
spec:
  match:
    kinds:
      - apiGroups: ["networking.istio.io"]
        kinds: ["Gateway"]
  parameters:
    approvedCipherSuites:
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
    maxTLSVersions: ["TLSV1_2"]
    minTLSVersions: ["TLSV1_2"]
    tlsModes: ["SIMPLE"]
