apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    role: edit
    user: alice@external.ca
  name: user-alice-external-clusterrole-edit
  namespace: alice
spec:
  rules:
  - when:
    - key: request.headers[kubeflow-userid]
      values:
      - alice@external.ca
