apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ProBAuth
metadata:
  name: deny-no-auth
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        - key: data.statcan.gc.ca/classification
          operator: In
          values:
            - protected-b
