apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    role: edit
    user: bob@external.ca
  name: user-bob-external-clusterrole-edit
  namespace: bob
spec:
  rules:
  - when:
    - key: request.headers[kubeflow-userid]
      values:
      - bob@external.ca
