apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: denyextraction
spec:
  crd:
    spec:
      names:
        kind: DenyExtraction
      validation:
        openAPIV3Schema:
          type: object
          properties:
            nodeLabels:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package denyextraction

        import data.kubernetes.node_labels
        
        same(a, b) {
          a == b
        }

        # If we can't load the node metadata,
        # then we need to reject the request since we can't confirm.
        violation[{"msg": msg}] {
          #subResources := ["attach", "exec"]

          data.inventory.metadata.labels.agentpool != "userpb"
          msg := sprintf("node_name %s.", [node_name])
          #msg := sprintf("blocking <%v>, cannot verify labels on node <%v/%v>", [input.review.requestSubResource, input.review.namespace, input.review.name])
        }

        violation[{"msg": msg}] {
          subResources := ["attach", "exec"]

          node := data.inventory
          sprintf("node: %v", [node])
          label := input.parameters.nodeLabels[_]

          matched := [found | found = node.metadata.labels[label.key] == label.value; found]
          count(matched) == count(input.parameters.nodeLabels)

          msg := sprintf("forbidden action <%v> on <%v/%v>", [input.review.requestSubResource, input.review.namespace, input.review.name])
        }
