apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  labels:
    state.aaw.statcan.gc.ca/has-sas-notebook-feature: "false"
  name: bob
spec:
  owner:
    kind: User
    name: bob@external.ca
  resourceQuotaSpec: {}
