# https://raw.githubusercontent.com/Azure/azure-policy/master/built-in-references/Kubernetes/ingress-hostnames-conflict/constraint.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressHostnamesConflict
metadata:
  name: ingress-hostnames-conflict
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
